export const ISSUER_IDENTITY_INSTRUCTION = 'issuer may be omitted; never invent issuer identity'

export const GUEST_MCP_INSTRUCTIONS = `Use the live MCP tool schemas as the capability authority for the connected Invompt workspace. Before tool use, complete explicit onboarding for either Guest mode with a server-issued pseudonymous local credential or separate registered OAuth over hosted HTTPS. Transport mode is separate from the current account type: hosted OAuth Guest and legacy credential Guest are both Guest principals. When the user explicitly asks to claim the active Guest workspace, call create_account_claim_link once; the backend decides whether the current account may claim it and returns any safe denial. If eligible, present claimUrl exactly once, explain that it expires, and never log or repeat it. After a successful browser claim, the OAuth grant stays connected and revalidates registered state; the old Guest credential fails closed with GUEST_ACCOUNT_CLAIMED. Do not retry or expose credentials, tokens, account identifiers, or internal claim identifiers. ${ISSUER_IDENTITY_INSTRUCTION} Omit every unknown identity field instead of synthesizing a placeholder. If get_invoice reports no active hosted link, use renew_invoice_link with a stable idempotency key; renewal replaces the public link without revising the invoice. send_invoice_email requires a registered account; a Guest connection returns FORBIDDEN, so call create_account_claim_link and reconnect with OAuth before sending. Confirm the recipient with the user before calling send_invoice_email; never echo the subject, message, or cc back to the user.`
/**
 * Keep this short, self-contained contract at the beginning of server instructions. Some hosts
 * do not read MCP resources or prompts before making their first tool call.
 */
export const STRUCTURED_INVOML_GUIDANCE =
  'create_invoice accepts exactly one: document (structured InvoML) or invoml (legacy JSON). document requires $invoml:"1.0", meta {documentType: invoice|quote|estimate|receipt|credit_note, number, issueDate, currency}, items {description, quantity, unitPrice}, and parties oneOf freeform {content:string} OR structured {name,address:{lines:[...]}}. Party forms must not mix; item.taxRate unsupported; taxCategory needs legacy. Recipients: list_clients first; never silently save. Create needs idempotencyKey.'
